# -*- coding: utf-8 -*-
def all_msg(lng='en'):
  return {
    'poïesys' : 'poïesys',
    'account' : 'Konto',
    'log out' : 'abmelden',
    'full screen' : 'vollbild',
    'change name' : 'Name ändern',
    'change email' : 'E-Mail-Adresse ändern',
    'change password' : 'Passwort ändern',
    'change language' : 'Sprache ändern',
    'upload avatar' : 'Avatar hochladen',
    'choose flag' : 'Flagge wählen',
    'log in' : 'anmelden',
    'register' : 'registrieren',
    'forgot password' : 'Passwort vergessen',
    'name' : 'Name',
    'email' : 'E-Mail-Adresse',
    'password' : 'Passwort',
    'language' : 'Sprache',
    'new name' : 'neuer Name',
    'new email' : 'neue E-Mail-Adresse',
    'new password' : 'neues Passwort',
    'old password' : 'altes Passwort',
    'confirm new email' : 'neue E-Mail-Adresse bestätigen',
    'confirm new password' : 'neues Passwort bestätigen',
    'email sent containing your password' : 'eine E-Mail mit Ihrem neuen Passwort wurde gesendet.',
    'logged in' : 'angemeldet',
    'logged out' : 'abgemeldet',
    'name changed' : 'Name wurde geändert',
    'email changed' : 'E-Mail wurde geändert',
    'password changed' : 'Passwort wurde geändert',
    'invalid email or password' : 'ungültige E-Mail-Adresse oder ungültiges Passwort',
    'account already exists' : 'dieses Konto existiert bereits',
    'account not found' : 'dieses Konto konnte nicht gefunden werden',
    'invalid password' : 'ungültiges Passwort',
    'email addresses do not match' : 'die E-Mail-Adressen stimmen nicht überein',
    'passwords do not match' : 'die Passwörter stimmen nicht überein',
    'no files selected' : 'keine Dateien ausgewählt',
    'type these words: delete this account' : 'geben sie diesen Satz ein: dieses Konto löschen',
    'delete account' : 'dieses Konto löschen',
    'this option will delete all your data permanently!' : 'diese Option wird all Ihre Daten permanent löschen!',
    'account deleted' : 'Konto wurde gelöscht',
    'text incorrect' : 'Text falsch' } if lng in ['de', 'gsw'] else {
    'account' : 'compte',
    'log out' : 'se déconnecter',
    'full screen' : 'plein écran',
    'upload avatar' : 'télécharger avatar',
    'choose flag' : 'choisissez le drapeau',
    'log in' : 'se connecter',
    'register' : 'enregistrement',
    'forgot password' : 'mot de passe oublié',
    'change name' : 'changer de nom',
    'change email' : "changer l'adresse de courrier électronique",
    'change password' : 'changer de mot de passe',
    'change language' : 'changer de langue',
    'name' : 'nom',
    'email' : 'courrier électronique',
    'password' : 'mot de passe',
    'language' : 'langue',
    'new name' : 'nouveau nom',
    'new email' : 'nouvelle adresse de courrier électronique',
    'new password' : 'nouveau mot de passe',
    'old password' : 'ancien mot de passe',
    'confirm new email' : 'confirmer la nouvelle adresse de courrier électronique',
    'confirm new password' : 'confirmer le nouveau mot de passe',
    'email sent containing your password' : 'courrier électronique contenant votre mot de passe envoyé',
    'logged in' : 'connecté',
    'logged out' : 'déconnecté',
    'name changed' : 'nom modifié',
    'email changed' : 'adresse de courrier électronique modifiée',
    'password changed' : 'mot de passe modifié',
    'invalid email or password' : 'adresse de courrier électronique ou mot de passe incorrect',
    'account already exists' : 'compte déjà existant',
    'account not found' : 'compte introuvable',
    'invalid password' : 'mot de passe incorrect',
    'email addresses do not match' : 'les adresses de courrier électronique ne correspondent pas',
    'passwords do not match' : 'les mots de passe ne correspondent pas',
    'no file selected' : 'aucun fichier sélectionné',
    'type these words: delete this account' : 'tapez ces mots: supprimer ce compte',
    'delete account' : 'supprimer compte',
    'this option will delete all your data permanently!' : 'cette option va supprimer vos données de façon permanente !',
    'account deleted' : 'compte supprimé',
    'text incorrect' : 'texte incorrect' } if lng in ['fr', 'fre', 'fra'] else {
    'poïesys' : 'poïesys',
    'account' : 'cuenta',
    'log out' : 'cerrar sesión',
    'full screen' : 'pantalla completa',
    'change name' : 'cambiar nombre',
    'change email' : 'cambiar email',
    'change password' : 'cambiar contraseña',
    'change language' : 'cambiar idioma',
    'upload avatar' : 'subir avatar',
    'choose flag' : 'escoger bandera',
    'log in' : 'iniciar sesión',
    'register' : 'registrar',
    'forgot password' : 'contraseña olvidada',
    'name' : 'nombre',
    'email' : 'email',
    'password' : 'contraseña',
    'language' : 'idioma',
    'new name' : 'nuevo nombre',
    'new email' : 'nuevo email',
    'new password' : 'nueva contraseña',
    'old password' : 'contraseña anterior',
    'confirm new email' : 'confirmar nuevo email',
    'confirm new password' : 'confirmar nueva contraseña',
    'email sent containing your password' : 'email enviado con tu contraseña',
    'logged in' : 'conectado',
    'logged out' : 'desconectado',
    'name changed' : 'nombre cambiado',
    'email changed' : 'email cambiado',
    'password changed' : 'contraseña cambiada',
    'invalid email or password' : 'email o contraseña inválido',
    'account already exists' : 'cuenta ya existe',
    'account not found' : 'cuenta no encontrada',
    'invalid password' : 'contraseña inválida',
    'email addresses do not match' : 'emails non coinciden',
    'passwords do not match' : 'contraseñas no coinciden',
    'no files selected' : 'archivos no seleccionados',
    'type these words: delete this account' : 'escribe estas palabras: eliminar esta cuenta',
    'delete account' : 'eliminar esta cuenta',
    'this option will delete all your data permanently!' : '¡esta opción borrará toda tu información permanentemente!',
    'account deleted' : 'cuenta eliminada',
    'text incorrect' : 'texto incorrecto' } if lng in ['es', 'spa'] else {
    'poïesys' : 'poïesys',
    'account' : 'conta',
    'log out' : 'sair sessão',
    'full screen' : 'tela cheia',
    'change name' : 'mudar nome',
    'change email' : 'mudar email',
    'change password' : 'mudar senha',
    'change language' : 'mudar língua',
    'upload avatar' : 'colocar imagem de perfil',
    'choose flag' : 'escolher bandeira',
    'log in' : 'entrar sessão',
    'register' : 'registrar',
    'forgot password' : 'senha esquecida',
    'name' : 'nome',
    'email' : 'email',
    'password' : 'senha',
    'language' : 'língua',
    'new name' : 'novo nome',
    'new email' : 'novo email',
    'new password' : 'nova senha',
    'old password' : 'antiga senha',
    'confirm new email' : 'confirmar novo email',
    'confirm new password' : 'confirmar nova senha',
    'email sent containing your password' : 'um email foi enviado com sua senha',
    'logged in' : 'conectado',
    'logged out' : 'desconectado',
    'name changed' : 'nome modificado',
    'email changed' : 'email modificado',
    'password changed' : 'senha modificada',
    'invalid email or password' : 'email ou senha inválidos',
    'account already exists' : 'essa conta já existe',
    'account not found' : 'conta não encontrada',
    'invalid password' : 'senha incorreta',
    'email addresses do not match' : 'os emails não coincidem',
    'passwords do not match' : 'as senhas não coincidem',
    'no file selected' : 'nenhum arquivo selecionado',
    'type these words: delete this account' : 'escreva estas palavras: deletar minha conta',
    'delete account' : 'deletar conta',
    'this option will delete all your data permanently!' : 'essa opção vai deletar todos os seus dados permanentemente!',
    'account deleted' : 'conta deletada',
    'text incorrect' : 'texto incorreto' } if lng in ['pt', 'por'] else {
    'poïesys' : 'поэзис',
    'account' : 'аккаунт',
    'log out' : 'выйти',
    'full screen' : 'полноэкранный',
    'change name' : 'изменить имя',
    'change email' : 'изменить э-мэйл',
    'change password' : 'изменить пароль',
    'change language' : 'изменить язык',
    'upload avatar' : 'загрузить аватар',
    'choose flag' : 'выбрать флаг',
    'log in' : 'вход',
    'register' : 'регистрация',
    'forgot password' : 'забыли пароль',
    'name' : 'имя',
    'email' : 'э-мэйл',
    'password' : 'пароль',
    'language' : 'язык',
    'new name' : 'новое имя',
    'new email' : 'новoe э-мэйл',
    'new password' : 'новый пароль',
    'old password' : 'старый пароль',
    'confirm new email' : 'подтвердить новый э-мэйл',
    'confirm new password' : 'подтвердить новый пароль',
    'email sent containing your password' : 'отправлено письмо с паролем',
    'logged in' : 'вошёл',
    'logged out' : 'вышёл',
    'name changed' : 'имя изменено',
    'email changed' : 'э-мэйл изменён',
    'password changed' : 'пароль изменен',
    'invalid email or password' : 'неверные э-мэйл или пароль',
    'account already exists' : 'аккаунт уже существует',
    'account not found' : 'аккаунт не найден',
    'invalid password' : 'пароль неверный',
    'email addresses do not match' : 'адреса электронной почты не совпадают',
    'passwords do not match' : 'пароли не совпадают',
    'no file chosen' : 'файл не выбран',
    'type these words: delete this account' : 'введите эти слова: удалить этот аккаунт',
    'delete account' : 'удалить аккаунт',
    'this option will delete all your data permanently!' : 'эта опция удалит все ваши данные навсегда!',
    'account deleted' : 'аккаунт удален',
    'text incorrect' : 'неверный текст' } if lng in ['ru', 'rus'] else {
    'poïesys' : 'poïesys',
    'account' : 'korisnički račun',
    'log out' : 'odjava',
    'full screen' : 'puni zaslon',
    'change name' : 'promijeni korisničko ime',
    'change email' : 'promijeni email adresu',
    'change password' : 'promijeni lozinku',
    'change language' : 'promijeni jezik',
    'upload avatar' : 'učitaj avatar',
    'choose flag' : 'odaberi zastavu',
    'log in' : 'prijava',
    'register' : 'kreiraj račun',
    'forgot password' : 'zaboravili ste lozinku',
    'name' : 'ime',
    'email' : 'email adresa',
    'password' : 'lozinka',
    'language' : 'jezik',
    'new name' : 'novo ime',
    'new email' : 'nova email adresa',
    'new password' : 'nova lozinka',
    'old password' : 'stara lozinka',
    'confirm new email' : 'potvrdi novu email adresu',
    'confirm new password' : 'potvrdi novu lozinku',
    'email sent containing your password' : 'poslan je email koji sadrži vašu lozinku',
    'logged in' : 'prijava uspješna',
    'logged out' : 'odjava uspješna',
    'name changed' : 'ime promijenjeno',
    'email changed' : 'email adresa promijenjena',
    'password changed' : 'lozinka promijenjena',
    'invalid email or password' : 'neispravna email adresa ili lozinka',
    'account already exists' : 'korisnički račun već postoji',
    'account not found' : 'korisnički račun nije pronađen',
    'invalid password' : 'neispravna lozinka',
    'email addresses do not match' : 'email adrese se ne podudaraju',
    'passwords do not match' : 'lozinke se ne podudaraju',
    'no file selected' : 'niste odabrali datoteku',
    'type these words: delete this account' : 'upišite sljedeće: izbriši ovaj korisnički račun',
    'delete account' : 'izbriši korisnički račun',
    'this option will delete all your data permanently!' : 'ova radnja će nepovratno izbrisati sve vaše podatke!',
    'account deleted' : 'korisnički račun uspješno izbrisan',
    'text incorrect' : 'netočan tekst' } if lng in ['hr', 'hrv', 'cnr', 'bs', 'bos', 'sr', 'srp'] else {
    'poïesys' : 'पोएसिस',
    'account' : 'लेखा',
    'log out' : 'लॉग आउट',
    'full screen' : 'पूर्ण स्क्रीन',
    'change name' : 'नाम परिवर्तित करें',
    'change email' : 'ईमेल बदलें',
    'change password' : 'पासवर्ड बदलें',
    'change language' : 'भाषा बदलो',
    'upload avatar' : 'अपलोड अवतार',
    'choose flag' : 'झंडा चुनें',
    'log in' : 'लॉग इन करें',
    'register' : 'रजिस्टर',
    'forgot password' : 'पासवर्ड भूल गए',
    'name' : 'नाम',
    'email' : 'ईमेल',
    'password' : 'पारण शब्द',
    'language' : 'भाषा',
    'new name' : 'नया नाम',
    'new email' : 'नई ईमेल',
    'new password' : 'नया पासवर्ड',
    'old password' : 'पुराना पासवर्ड',
    'confirm new email' : 'नई ईमेल की पुष्टि करें',
    'confirm new password' : 'नए पासवर्ड की पुष्टि करें',
    'email sent containing your password' : 'आपके पासवर्ड युक्त ईमेल भेजा गया',
    'logged in' : 'में लॉग इन',
    'logged out' : 'बाहर आ गये',
    'name changed' : 'नाम बदला',
    'email changed' : 'ईमेल परिवर्तित',
    'password changed' : 'पासवर्ड बदला गया',
    'invalid email or password' : 'अमान्य ईमेल या पासवर्ड',
    'account already exists' : 'खाता पहले से मौजूद है',
    'account not found' : 'खता नहीं मिला',
    'invalid password' : 'अवैध पासवर्ड',
    'email addresses do not match' : 'ईमेल एड्रेस मैच नहीं हो रहा है',
    'passwords do not match' : 'पासवर्ड मेल नहीं खाते',
    'no file selected' : 'कोई भी फाइल नहीं चुनी गई',
    'type these words: delete this account' : 'ये शब्द लिखें: इस खाते को हटाएं',
    'delete account' : 'खाता हटा दो',
    'this option will delete all your data permanently!' : 'यह विकल्प आपके सभी डेटा को स्थायी रूप से हटा देगा!',
    'account deleted' : 'खाता हटा दिया गया',
    'text incorrect' : 'पाठ गलत' } if lng in ['hi', 'hin'] else {
    'poïesys' : 'poïesys',
    'account' : 'account',
    'log out' : 'log out',
    'full screen' : 'full screen',
    'change name' : 'change name',
    'change email' : 'change email',
    'change password' : 'change password',
    'change language' : 'change language',
    'upload avatar' : 'upload avatar',
    'choose flag' : 'choose flag',
    'log in' : 'log in',
    'register' : 'register',
    'forgot password' : 'forgot password',
    'name' : 'name',
    'email' : 'email',
    'password' : 'password',
    'language' : 'language',
    'new name' : 'new name',
    'new email' : 'new email',
    'new password' : 'new password',
    'old password' : 'old password',
    'confirm new email' : 'confirm new email',
    'confirm new password' : 'confirm new password',
    'email sent containing your password' : 'email sent containing your password',
    'logged in' : 'logged in',
    'logged out' : 'logged out',
    'name changed' : 'name changed',
    'email changed' : 'email changed',
    'password changed' : 'password changed',
    'invalid email or password' : 'invalid email or password',
    'account already exists' : 'account already exists',
    'account not found' : 'account not found',
    'invalid password' : 'invalid password',
    'email addresses do not match' : 'email addresses do not match',
    'passwords do not match' : 'passwords do not match',
    'no file selected' : 'no file selected',
    'type these words: delete this account' : 'type these words: delete this account',
    'delete account' : 'delete account',
    'this option will delete all your data permanently!' : 'this option will delete all your data permanently!',
    'account deleted' : 'account deleted',
    'text incorrect' : 'text incorrect' }
